### ISSUE TITLE
Add operator== and != to EXPRESSObject

### ISSUE THREAD

**Issue by pjanck** [tumcms/Open-Infra-Platform#126]
In order for std::find and other to work, these functions are needed.

**Comment by hechth** [comment]
It would be nice to see an example where this would be used in order to test it.

**Comment by pjanck** [comment]
https://github.com/tumcms/Open-Infra-Platform/blob/4ac4f5b7c8081634833b4a3c0553572b8d4f8cfa/Core/src/IfcGeometryConverter/PlacementConverter.h#L755-L758
