### ISSUE TITLE
[REF] ProfileConverter.h

### ISSUE THREAD

**Issue by hechth** [tumcms/Open-Infra-Platform#135]
**File which is being refactored**
Refactor IfcGeometryConverter\ProfileConverter.h

- [ ] Add all functions which have to be refactored or are refactored!

**Comment by SamuilsRulovs** [comment]
- [ ] convertIfcArbitraryClosedProfileDef
- [ ] convertIfcArbitraryOpenProfileDef
- [ ] convertIfcCompositeProfileDef
- [ ] convertIfcDerivedProfileDef
- [ ] convertIfcParameterizedProfileDef
- [ ] convertIfcArbitraryProfileWithVoids
- [ ] convertIfcParameterizedProfileDefWithPosition

**Comment by pjanck** [comment]
Fixed through #127 .
