### ISSUE TITLE
[REF] SectionedSolidHorizontal

### ISSUE THREAD

**Issue by hechth** [tumcms/Open-Infra-Platform#138]
**File which is being refactored**
IfcGeometryConverter\SolidModelConverter.h

**Functions**

List all functions in the file which have to be refactored with possible code snippets!

- [ ] Listed all functions in the issue.

**Comment by pjanck** [comment]
To clarify: your task is only to implement (the not yet implemented) conversion of IfcSectionedSolidHorizontal. If you find the time and want to, you may refactor other stuff within the whole geometry conversion part of OIP.
