### ISSUE TITLE
[REF] SplineConverter.h

### ISSUE THREAD

**Issue by hechth** [tumcms/Open-Infra-Platform#139]
**File which is being refactored**
IfcGeometryConverter\SplineConverter.h

**Functions**

List all functions in the file which have to be refactored with possible code snippets!

- [ ] Listed all functions in the issue.

**Comment by christophKaiser** [comment]
Functions in refactoring:
- [x] convertIfcBSplineCurve including its specialized template function
- [ ] convertIfcBSplineSurface including its specialized template function
- [x] computeBSplineBasisFunctions
- [ ] computeBSplineSurface
- [x] computeBSplineCurve

[Updated 2020-07-21]
