### ISSUE TITLE
[BUG] Application crashes when loading two IFC files sequentially

### ISSUE THREAD

**Issue by hechth** [tumcms/Open-Infra-Platform#149]
**Describe the bug**
The application crashes when two IFC files are loaded after another.
Tested with example files [surface-model.ifc](https://github.com/tumcms/Open-Infra-Platform/blob/development/testdata/IFC4x1ExampleFiles/official/E2_Basic_geometric_shape/surface-model.ifc) and [tessellated-item.ifc](https://github.com/tumcms/Open-Infra-Platform/blob/development/testdata/IFC4x1ExampleFiles/official/E2_Basic_geometric_shape/tessellated-item.ifc).

**To Reproduce**
1. Start application.
2. Open first file.
3. Open second file.
4. See error [log.txt](https://github.com/tumcms/Open-Infra-Platform/files/4680131/log.txt)

**Expected behavior**
Both files should open normally after another.

**CMake configuration**
 If applicable, list any special configurations you have made in CMake.
- EARLYBINDING_WITH_IFC4x1: selected

**Additional context**
See [log.txt](https://github.com/tumcms/Open-Infra-Platform/files/4680131/log.txt)

**Comment by pjanck** [comment]
See also #108 .
