### ISSUE TITLE
[REF] Refactor ProfileConverter.h 

### ISSUE THREAD

**Issue by SamuilsRulovs** [tumcms/Open-Infra-Platform#152]
**File which is being refactored**
ProfileConverter.h 
**Functions**

- [ ] convertIfcArbitraryClosedProfileDef
- [ ] convertIfcArbitraryOpenProfileDef
- [ ] convertIfcCompositeProfileDef
- [ ] convertIfcDerivedProfileDef
- [ ] convertIfcParameterizedProfileDef
- [ ] convertIfcArbitraryProfileWithVoids
- [ ] convertIfcParameterizedProfileDefWithPosition

**Comment by pjanck** [comment]
Resolved by #127 .
