### ISSUE TITLE
[REF] Use base class functions for common attribute functionality

### ISSUE THREAD

**Issue by hechth** [tumcms/Open-Infra-Platform#203]
**File which is being refactored**
GeneratorOIP.cpp

**Functions**
- [ ] generateEntitySourceFileREFACTORED
- [ ] generateEntityHEaderFileREFACTORED

Writing of swap function, assignment operator, ReadStepData, GetStepLine has to be refactored in order to use base class functions so that not all attributes have to be reference or therefore included in the class.

**Comment by pjanck** [comment]
Retired - see #210 .
