### ISSUE TITLE
[BUG] Compilation of IFC4x1 fails due to PreferencesDialog

### ISSUE THREAD

**Issue by ghost** [tumcms/Open-Infra-Platform#224]
**Describe the bug**
The compilation of the IFC4x1 schema fails due to the PreferencesDialog. There seems to be an include missing / outdated.

**To Reproduce**
1. Select IFC4x1 as schema in CMake
2. Configure, generate, open project.
3. Start building the IFC4x1 schema.

**Screenshots**

![image](https://user-images.githubusercontent.com/60961975/90682747-bc7b6880-e265-11ea-9a80-4230a3a0d88a.png)

**CMake configuration**
 If applicable, list any special configurations you have made in CMake.
- EARLYBINDING_WITH_IFC4x1: selected

**Comment by pjanck** [comment]
Hi @ccoetzee - please try the following:
- delete folders `blue-framework-*` in `CMake_Binary_Dir/_deps`
- generate the solution anew
- build anew

The problem should go away.

**Comment by ghost** [comment]
The problem was solved by deleting the folders mentioned by @pjanck and generating and building anew.
