### ISSUE TITLE
Reintroduce interpretation of openings

### ISSUE THREAD

**Issue by pjanck** [tumcms/Open-Infra-Platform#34]
Through the refactoring of IFC, these part was commented out. The openings within geometries need to be reintroduced.

https://github.com/tumcms/Open-Infra-Platform/blob/bbf56fdee1043788448ff622879e7f2f5a4b8446/Core/src/IfcGeometryConverter/RepresentationConverter.h#L601-L666

**Comment by kyq** [comment]
![image](https://user-images.githubusercontent.com/10072861/79386708-6cf8f900-7f62-11ea-8210-fc57eed33f5e.png) This figure illustrates the issue. On the left hand, the hole is visible (boolean "difference" operation properly applied), while the opening is not shown in OIP (right hand window).
