### ISSUE TITLE
Parse "INVERSE" attributes from IFC schema

### ISSUE THREAD

**Issue by pjanck** [tumcms/Open-Infra-Platform#35]
Many (previously existing) functionalities can only be implemented, when the INVERSE attributes in the IFC schema are parsed and corresponding members generated. One of such functionalities is #34 .

**Comment by hechth** [comment]
* Test inverses on a small subschema

**Comment by pjanck** [comment]
Adapted the example from [Wikipedia](https://en.wikipedia.org/wiki/EXPRESS_(data_modeling_language)):

SCHEMA Family;

ENTITY Person
   ABSTRACT SUPERTYPE OF (ONEOF (Male, Female));
     name: STRING;
     mother: OPTIONAL Female;
     father: OPTIONAL Male;
END_ENTITY;

ENTITY Female
   SUBTYPE OF (Person);
 INVERSE
    MotherToPerson : SET [0:?] OF Person FOR mother;
END_ENTITY;

ENTITY Male
   SUBTYPE of (Person);
 INVERSE
    FatherToPerson : SET [0:?] OF Person FOR father;
END_ENTITY;

END_SCHEMA;
