### ISSUE TITLE
[DOCUMENTATION] Qt Version compatibility range

### ISSUE THREAD

**Issue by CBenghi** [tumcms/Open-Infra-Platform#450]
**Describe the bug**
Version 5.12.1 does not seem available from the current QT installer

**To Reproduce**
On windows;
1. Download current qt installer
2. See the missing checkbox in the installer UI

**Expected behavior**
A range of compatible QT libraries should be listed so that users can safely choose a version in the current setup.

**Screen shot**
![image](https://user-images.githubusercontent.com/5476273/117858534-43f28700-b28e-11eb-8cc4-7e0603bf91d5.png)

**Comment by pjanck** [comment]
Please select the option "Archive" under "Select Categories".

**Comment by pjanck** [comment]
As for 

> A range of compatible QT libraries should be listed so that users can safely choose a version in the current setup.

We did not (yet) have the time to test which versions would still be supported. Our wish is to upgrade to the latest releases with #319 , so it was deemed unnecessary work.

**Comment by CBenghi** [comment]
Hi @pjanck. 
Super helpful.
I was just not familiar with the qt installer options, no need to specify the range if 5.12.1 can be found in the archive.
Maybe just update the docs to reflect the need to check the archive flag. A newbie like me could be discouraged.
Thanks

**Comment by pjanck** [comment]
It is there ;)

![grafik](https://user-images.githubusercontent.com/59165496/117860987-34287200-b291-11eb-9b3a-6ead8a8fb9e2.png)

But I see that I need to update the screen shot - I wasn't aware of the UI update for their installer.

**Comment by CBenghi** [comment]
Lol. Sorry!

**Comment by CBenghi** [comment]
See #451 as a way to apologise.
C

**Comment by pjanck** [comment]
Apologies accepted! Thank you for the updated graphic and the bib!
