### ISSUE TITLE
[BUG] Precompiled binaries (package missing dll)

### ISSUE THREAD

**Issue by CBenghi** [tumcms/Open-Infra-Platform#453]
**Describe the bug**
Execution of the pre-compiled binaries fail, for missing dll.

**To Reproduce**
1. Install the binaries freshly dowloaded
2. Launch

**Expected behavior**
Application starts :-D

**Screen shot**
![image](https://user-images.githubusercontent.com/5476273/117957546-7a75e380-b31a-11eb-9809-6d928801e883.png)

**Comment by pjanck** [comment]
Have you compiled all projects in the Copy folder?

**Comment by CBenghi** [comment]
Hi, I've managed to run my compilation, this is an issue of the pre-compiled installer.

**Comment by pjanck** [comment]
I'm not completely following you here. Are you trying to start the application using the debugger within Visual Studio or somehow differently?

**Comment by CBenghi** [comment]
I've downloaded the binaries from from http://oip.cms.bgu.tum.de/TUM%20Open%20Infra%20Platform.msi
It's linked from some page in your docs.

**Comment by CBenghi** [comment]
I wanted to see if the pre-compiled version was capable of managing multiple IFC schemas, from our call I got the impression that only a single IFC version can be used at a time.

**Comment by pjanck** [comment]
> I've downloaded the binaries from from http://oip.cms.bgu.tum.de/TUM%20Open%20Infra%20Platform.msi It's linked from some page in your docs.

Right, I see. Two things to note here:

1. This is an installer of the old, *pre-refactoring*  version (the state of the `master` branch). This is a known issue (with the missing zlib), that is described in the old repository: https://github.com/tumcms/OpenInfraPlatform#buildng-thirdparty-libararies . 
2. The newer development foresees a an update of the installer, however, we have not yet got around to produce one. Currently, the only way to use OIP with the new architecture, is to compile it yourself (see also https://github.com/bSI-InfraRoom/IFC-infra-unit-test/issues/114)

And a question: where is the installer linked? I need to remove that (or better describe the state).

> I wanted to see if the pre-compiled version was capable of managing multiple IFC schemas, from our call I got the impression that only a single IFC version can be used at a time.

- For the installer: Yes and no. IfcWalls only got interpreted in version 2x3, while alignments only in 4x1. 
- For the current version: Only one IFC version at a time, however the full scope.

**Comment by CBenghi** [comment]
I think it's in `Open-Infra-Platform/Documentation/markdown/User.md`

**Comment by pjanck** [comment]
I see. Thank you for the hint - I've updated the document itself in 3341b51.

There was a note on the state of the document in the main readme (stating "out-of-sync"), however no note in the document itself.

**Comment by CBenghi** [comment]
Sure, 
for the review I need to check for
`Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).`
So I've tried following that path too...

Is there some other place in the repository where I can find that?

**Comment by CBenghi** [comment]
Never mind, I've found the doc file with end user documentation. 
Provided it's current I'm happy to check the flag.

**Comment by pjanck** [comment]
The end user documentation is par-on-par with the installer and describes how to use the software in that stage. It needs updating with the update of the installer, though.
