### ISSUE TITLE
[BUG] Link to OSGeo4W64 installer gives 404 error

### ISSUE THREAD

**Issue by RickBrice** [tumcms/Open-Infra-Platform#464]
Trying to build OIP. In instructions for PROJ, the link for the OSGEO4W64 program gives a 404 error.

**Comment by jschlenger** [comment]
Thanks for reporting the issue. We are working on it.

**Comment by pjanck** [comment]
The problem was identified. The solution will come with #319 , so please be patient in the meantime.
