### ISSUE TITLE
[BUG] Get_OKLABI.cmd is not working properly

### ISSUE THREAD

**Issue by SamuilsRulovs** [tumcms/Open-Infra-Platform#480]
**Describe the bug**
Get_OKLABI.cmd should be updated, thus it could download new version of OKLABI

**To Reproduce**
1. In File Explorer open source folder
2. Open "external" folder
3. Click on "Get_OKLABI.cmd"

**Expected behavior**
Though this program OKLABI should be installed in C:\thirdparty\vs2015\x64  

**Additional context**

**Comment by jschlenger** [comment]
We used OKLABI to support the OKSTRA format. Since we are currently not supporting it anymore this step of executing Get_Oklabi.cmd can be skipped. I already adjusted this in the new documentation that will come with the VS2019 update.

**Comment by SamuilsRulovs** [comment]
Ok, however during Installation of OIP with @Elvira2227, we always had some issues building it, until I sent her my OKLABI files (since she could not download it herself through get_OKLABI.cmd anymore)

**Comment by jschlenger** [comment]
Thanks for letting me know. I will double check that with VS 2019 it will work without using get_OKLABI.cmd.

**Comment by jschlenger** [comment]
With VS2019 get_OKLABI.cmd is not needed anymore.
