### ISSUE TITLE
Example file "polygonal-face-tessellation" not rendered.

### ISSUE THREAD

**Issue by SamuilsRulovs** [tumcms/Open-Infra-Platform#61]
The file is [here](../blob/development/testdata/IFC4x1ExampleFiles/official/E4_Tessellated_shape/polygonal-face-tessellation.ifc).  OIP doesn't show anything.

**Comment by SamuilsRulovs** [comment]
As of today, still not rendered

**Comment by pjanck** [comment]
This should be working after merging #322 . Please provide a unit test.
