### ISSUE TITLE
Group projects in the solution to make it look clean

### ISSUE THREAD

**Issue by pjanck** [tumcms/Open-Infra-Platform#7]
Currently, all projects belonging to OpenInfraPlatform are grouped nicely in a OpenInfraPlatform folder:

![image](https://user-images.githubusercontent.com/59165496/78757235-78558e80-797c-11ea-9ea9-e24d27bb4a0e.png)

I would like to see other projects currently wildly swimming around grouped as well, in order to minimize confusion:

![grafik](https://user-images.githubusercontent.com/59165496/78757384-b18dfe80-797c-11ea-932f-781b572c97e3.png)

**Comment by hechth** [comment]
Slight imrpovement by #52
