### ISSUE TITLE
Example file "beam-varying-extrusion-paths" is not working

### ISSUE THREAD

**Issue by SamuilsRulovs** [tumcms/Open-Infra-Platform#71]
The file is [here](../blob/development/testdata/IFC4x1ExampleFiles/official/E14_Additional_test_cases/beam-varying-extrusion-paths.ifc). Current version crashes.

**Comment by SamuilsRulovs** [comment]
It works slightly better, now it doesn't show anything

**Comment by pjanck** [comment]
After merging #258 it now shows:

![grafik](https://user-images.githubusercontent.com/59165496/99088169-f68da980-25cb-11eb-9995-3aaf95458eaa.png)
